url: https://preview.catalogueoflife.org
react:
    auth: "coldeploy:g2o.d43svHngu4HsEp7Xwlö"

metadata:
  key: 3
  private: true
  api: https://api.checklistbank.org
  user: coldeploy
  pass: g2o.d43svHngu4HsEp7Xwlö
  # email: col@mailinator.com
