react:
    datasetKey: "3RC" # Which dataset should the tree and search components use?

milestones:
  items:
    - count: //api.catalogue.life/dataset/3RC/nameusage/search?TAXON_ID=061950e4-9782-4d1a-9c87-dcf375788e6b&limit=0&rank=species&status=accepted&status=provisionally%20accepted
    - count: //api.catalogue.life/dataset/3RC/nameusage/search?TAXON_ID=fc995438-b561-4616-a896-f479fca6e3d4&limit=0&rank=species&status=accepted&status=provisionally%20accepted
    - count: //api.catalogue.life/dataset/3RC/nameusage/search?TAXON_ID=d64f9d40-cbe5-4908-b4c2-16a9d6429401&limit=0&rank=species&status=accepted&status=provisionally%20accepted   
    - count: //api.catalogue.life/dataset/3RC/nameusage/search?TAXON_ID=dc38164e-ddff-4305-85a1-b320a0216cef&TAXON_ID=56f9bfb4-e63c-4ef7-b8e5-66f40b9233cd&TAXON_ID=63e291b2-9018-4cdb-a599-ed6404d06ab4&TAXON_ID=7b3a7eb4-e311-4521-813b-c288e408e005&TAXON_ID=4f6fabd6-2431-4a77-b77f-de60e4a7accc&limit=0&rank=species&status=accepted&status=provisionally%20accepted