# Site settings
title: COL
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Catalogue of Life
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: catalogueoflife
facebook_username:  CatalogueOfLife

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "news/page:num"

exclude: ["vendor", "/theme-examples", "/**/README.md", "bundle"]

include: ["_redirects", ".htaccess"]

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-get-json

permalink: /:year/:month/:day/:title.html

toc:
  min_level: 1 # default: 1
  max_level: 2 # default: 6

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

col:
  defaultImageUrl: /images/default-bg.jpg
  defaultImageCaption: "[A description](https://www.some.org/where) would go here ([CC BY-NC 4.0](http://creativecommons.org/licenses/by-nc/4.0/))"
  datasetKey: 3

react:
    datasetKey: "3LR" # Which dataset should the tree and search components use?
    pathToTaxon: "/data/taxon/" # path to the taxon page for crosslinking between react components
    pathToTree: "/data/browse" # path to the tree browser for crosslinking between react components
    pathToSearch: "/data/search" # path to the search page for crosslinking between react components
    pathToDataset: "/data/dataset/" # path to the dataset page for crosslinking between react components


milestones:
  items:
    - image: Podarcis.jpg
      count: //api.catalogue.life/dataset/3LR/nameusage/search?TAXON_ID=061950e4-9782-4d1a-9c87-dcf375788e6b&limit=0&rank=species&status=accepted&status=provisionally%20accepted
      selector: total
      title: Animalia
      bgcolor: 0480b5
      fgcolor: ccedfa
      link: /index.html?taxonKey=061950e4-9782-4d1a-9c87-dcf375788e6b
    - image: Pultenaea.jpg
      count: //api.catalogue.life/dataset/3LR/nameusage/search?TAXON_ID=fc995438-b561-4616-a896-f479fca6e3d4&limit=0&rank=species&status=accepted&status=provisionally%20accepted
      selector: total
      title: Plantae
      bgcolor: d0bd34
      fgcolor: fcfbe7
      link: /index.html?taxonKey=fc995438-b561-4616-a896-f479fca6e3d4
    - image: Teloschistes.jpg
      count: //api.catalogue.life/dataset/3LR/nameusage/search?TAXON_ID=d64f9d40-cbe5-4908-b4c2-16a9d6429401&limit=0&rank=species&status=accepted&status=provisionally%20accepted
      selector: total
      title: Fungi
      bgcolor: e83143
      fgcolor: feebed
      link: /index.html?taxonKey=d64f9d40-cbe5-4908-b4c2-16a9d6429401
    - image: Protozoa.jpg
      count: //api.catalogue.life/dataset/3LR/nameusage/search?TAXON_ID=dc38164e-ddff-4305-85a1-b320a0216cef&TAXON_ID=56f9bfb4-e63c-4ef7-b8e5-66f40b9233cd&TAXON_ID=63e291b2-9018-4cdb-a599-ed6404d06ab4&TAXON_ID=7b3a7eb4-e311-4521-813b-c288e408e005&TAXON_ID=4f6fabd6-2431-4a77-b77f-de60e4a7accc&limit=0&rank=species&status=accepted&status=provisionally%20accepted
      selector: total
      title: Other kingdoms
      bgcolor: 2db261
      fgcolor: ecf7ef
      link: /index.html?taxonKey=0

jekyll_get_json:
  - data: colversion
    json: 'https://api.catalogue.life/dataset/3LR'