# Site settings
title: COL
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Catalogue of Life
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: catalogueoflife
facebook_username:  CatalogueOfLife

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "news/page:num"

exclude: ["vendor", "/theme-examples", "/**/README.md", "bundle"]

include: ["_redirects", ".htaccess"]

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives


permalink: /:year/:month/:day/:title.html

toc:
  min_level: 1 # default: 1
  max_level: 2 # default: 6

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

col:
  defaultImageUrl: /images/default-bg.jpg
  defaultImageCaption: "[A description](https://www.some.org/where) would go here ([CC BY-NC 4.0](http://creativecommons.org/licenses/by-nc/4.0/))"
  datasetKey: 3

react:
    datasetKey: "3LR" # Which dataset should the tree and search components use?
    pathToTaxon: "/data/taxon/" # path to the taxon page for crosslinking between react components
    pathToTree: "/data/browse" # path to the tree browser for crosslinking between react components
    pathToSearch: "/data/search" # path to the search page for crosslinking between react components
    pathToDataset: "/data/dataset/" # path to the dataset page for crosslinking between react components