# Site settings
title: COL
email: feedback@catalogueoflife.org
description: > # this means to ignore newlines until "baseurl:"
  The Catalogue of Life
# https://mademistakes.com/mastering-jekyll/site-url-baseurl/
url: https://www.catalogueoflife.org
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: catalogueoflife
facebook_username:  CatalogueOfLife

# SEO plugin settings
twitter:
  username: catalogueoflife
  card: summary
social:
  name: The Catalogue of Life
  links:
    - https://twitter.com/catalogueoflife
    - https://www.facebook.com/CatalogueOfLife
    - https://github.com/CatalogueOfLife
logo: /images/logos/col_square_logo.jpg

# Build settings
markdown: kramdown

paginate: 5
paginate_path: "news/page:num"

exclude: ["vendor", "/theme-examples", "/**/README.md", "bundle"]

include: ["_redirects", ".htaccess"]

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

permalink: /:year/:month/:day/:title

toc:
  min_level: 1 # default: 1
  max_level: 2 # default: 6

future: false
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

col:
  defaultImageUrl: /images/default-bg.jpg
  defaultImageCaption: "[A description](https://www.some.org/where) would go here ([CC BY-NC 4.0](http://creativecommons.org/licenses/by-nc/4.0/))"
  datasetKey: 3

milestones:
  items:
    - image: Podarcis.jpg
      count: //api.checklistbank.org/dataset/3LR/nameusage/search?TAXON_ID=N&limit=0&rank=species&status=accepted&status=provisionally%20accepted
      selector: total
      title: Animalia
      bgcolor: 0480b5
      fgcolor: ccedfa
      link: /index?taxonKey=N
    - image: Pultenaea.jpg
      count: //api.checklistbank.org/dataset/3LR/nameusage/search?TAXON_ID=P&limit=0&rank=species&status=accepted&status=provisionally%20accepted
      selector: total
      title: Plantae
      bgcolor: d0bd34
      fgcolor: fcfbe7
      link: /index?taxonKey=P
    - image: Teloschistes.jpg
      count: //api.checklistbank.org/dataset/3LR/nameusage/search?TAXON_ID=F&limit=0&rank=species&status=accepted&status=provisionally%20accepted
      selector: total
      title: Fungi
      bgcolor: e83143
      fgcolor: feebed
      link: /index?taxonKey=F
    - image: Protozoa.jpg
      count: //api.checklistbank.org/dataset/3LR/nameusage/search?TAXON_ID=V&TAXON_ID=R&TAXON_ID=B&TAXON_ID=C&TAXON_ID=Z&limit=0&rank=species&status=accepted&status=provisionally%20accepted
      selector: total
      title: Other kingdoms
      bgcolor: 2db261
      fgcolor: ecf7ef
      link: /index?taxonKey=Z

react:
    datasetKey:  # Will be set via the metadata loading plugin - which dataset should the tree and search components use?
    pathToTaxon: "/data/taxon/" # path to the taxon page for crosslinking between react components
    pathToTree: "/data/browse" # path to the tree browser for crosslinking between react components
    pathToSearch: "/data/search" # path to the search page for crosslinking between react components
    pathToDataset: "/data/dataset/" # path to the dataset page for crosslinking between react components
    auth: "coldeploy:g2o.d43svHngu4HsEp7Xwlo"

metadata:
  key: 3
  private: false
  api: https://api.checklistbank.org

changelog:
  limit: 100
