url: https://preview.catalogueoflife.org
react:
    auth: "col-preview-portal:RXY7BdP-w!Fkat8g"

metadata:
  key: 3
  private: true
  api: https://api.checklistbank.org
  user: col-preview-portal
  pass: RXY7BdP-w!Fkat8g
