import { readdirSync } from 'node:fs';
import { join } from 'node:path';
import { site } from '@lib/site';

export const prerender = true;

// SITE_ENV gates indexing: only prod is crawlable (was jekyll.environment).
const env = process.env.SITE_ENV ?? 'prod';

export function GET() {
  const headers = { 'Content-Type': 'text/plain' };
  if (env !== 'prod') {
    return new Response('User-agent: *\nDisallow: /\n', { headers });
  }
  const lines = [
    'User-agent: *',
    'crawl-delay: 0.1',
    '',
    'Disallow: /annual-checklist',
    '',
    `Sitemap: ${site.url}/sitemap.txt`,
    `Sitemap: ${site.url}/sitemap-datasets.txt`,
  ];
  // List the chunked taxon sitemaps generated by scripts/update-sitemaps.sh.
  try {
    const dir = join(process.cwd(), 'public', 'sitemaps');
    for (const f of readdirSync(dir).filter((f) => f.endsWith('.gz')).sort()) {
      lines.push(`Sitemap: ${site.url}/sitemaps/${f}`);
    }
  } catch {
    /* no sitemaps generated yet */
  }
  return new Response(lines.join('\n') + '\n', { headers });
}
